const symbolMappings = {
	'00': { name: '00 Token', slug: '00-token' },
	'1INCH': { name: '1inch', slug: '1inch' },
	A8: { name: 'A8Coin', slug: 'a8coin' },
	AAVE: { name: 'Aave', slug: 'aave' },
	ABT: { name: 'Arcblock', slug: 'arcblock' },
	ACH: { name: 'Alchemy Pay', slug: 'alchemy-pay' },
	ACS: { name: 'ACryptoS', slug: 'acryptos' },
	ACX: { name: 'Across Protocol', slug: 'across-protocol' },
	ADA: { name: 'Cardano', slug: 'cardano' },
	AERGO: { name: 'Aergo', slug: 'aergo' },
	AERO: { name: 'Aerodrome Finance', slug: 'aerodrome-finance' },
	AIOZ: { name: 'AIOZ Network', slug: 'aioz-network' },
	AKT: { name: 'Akash Network', slug: 'akash-network' },
	ALEPH: { name: 'Aleph.im', slug: 'aleph-im' },
	ALGO: { name: 'Algorand', slug: 'algorand' },
	ALICE: { name: 'MyNeighborAlice', slug: 'my-neighbor-alice' },
	ALT: { name: 'AltLayer', slug: 'altlayer' },
	AMP: { name: 'Amp', slug: 'amp' },
	ANKR: { name: 'Ankr', slug: 'ankr' },
	APE: { name: 'ApeCoin', slug: 'apecoin' },
	API3: { name: 'API3', slug: 'api3' },
	APT: { name: 'Aptos', slug: 'aptos' },
	ARB: { name: 'Arbitrum', slug: 'arbitrum' },
	ASM: { name: 'Assemble Protocol', slug: 'assemble-protocol' },
	AST: { name: 'AirSwap', slug: 'airswap' },
	ATH: { name: 'Aetherius', slug: 'aetherius' },
	ATOM: { name: 'Cosmos', slug: 'cosmos' },
	AUCTION: { name: 'Bounce Token', slug: 'bounce-token' },
	AUDIO: { name: 'Audius', slug: 'audius' },
	AURORA: { name: 'Aurora', slug: 'aurora' },
	AVAX: { name: 'Avalanche', slug: 'avalanche' },
	AVT: { name: 'Aventus', slug: 'aventus' },
	AXL: { name: 'Axelar', slug: 'axelar' },
	AXS: { name: 'Axie Infinity', slug: 'axie-infinity' },
	BAL: { name: 'Balancer', slug: 'balancer' },
	BAT: { name: 'Basic Attention Token', slug: 'basic-attention-token' },
	BCH: { name: 'Bitcoin Cash', slug: 'bitcoin-cash' },
	BIGTIME: { name: 'Big Time', slug: 'big-time' },
	BLAST: { name: 'Blast', slug: 'blast' },
	BLUR: { name: 'Blur', slug: 'blur' },
	BLZ: { name: 'Bluzelle', slug: 'bluzelle' },
	BOBA: { name: 'Boba Network', slug: 'boba-network' },
	BOND: { name: 'BarnBridge', slug: 'barnbridge' },
	BONK: { name: 'Bonk', slug: 'bonk' },
	BTC: { name: 'Bitcoin', slug: 'bitcoin' },
	C98: { name: 'Coin98', slug: 'coin98' },
	CBETH: { name: 'Coinbase Wrapped Staked ETH', slug: 'coinbase-wrapped-staked-eth' },
	CCD: { name: 'Concordium', slug: 'concordium' },
	CELR: { name: 'Celer Network', slug: 'celer-network' },
	CFG: { name: 'Centrifuge', slug: 'centrifuge' },
	CGLD: { name: 'Celo', slug: 'celo' },
	CHEX: { name: 'Chintai', slug: 'chintai' },
	CLOUD: { name: 'Cloudname', slug: 'cloudname' },
	CLV: { name: 'Clover Finance', slug: 'clover-finance' },
	COMP: { name: 'Compound', slug: 'compound' },
	COQ: { name: 'Coq Inu', slug: 'coq-inu' },
	CORECHAIN: { name: 'Core Chain', slug: 'core-chain' },
	COTI: { name: 'COTI', slug: 'coti' },
	COW: { name: 'CoW Protocol', slug: 'cow-protocol' },
	CPOOL: { name: 'Clearpool', slug: 'clearpool' },
	CRO: { name: 'Cronos', slug: 'cronos' },
	CRV: { name: 'Curve DAO Token', slug: 'curve-dao-token' },
	CTSI: { name: 'Cartesi', slug: 'cartesi' },
	CTX: { name: 'Cryptex Finance', slug: 'cryptex-finance' },
	CVX: { name: 'Convex Finance', slug: 'convex-finance' },
	CXT: { name: 'CoinMetro', slug: 'coinmetro' },
	DAI: { name: 'Dai', slug: 'dai' },
	DEGEN: { name: 'Degen', slug: 'degen' },
	DIA: { name: 'DIA', slug: 'dia' },
	DIMO: { name: 'DIMO', slug: 'dimo' },
	DOGE: { name: 'Dogecoin', slug: 'dogecoin' },
	DOT: { name: 'Polkadot', slug: 'polkadot' },
	DRIFT: { name: 'Drift Protocol', slug: 'drift-protocol' },
	DSH: { name: 'Dash', slug: 'dash' },
	DYM: { name: 'Dymension', slug: 'dymension' },
	EGLD: { name: 'MultiversX', slug: 'multiversx' },
	EIGEN: { name: 'EigenLayer', slug: 'eigenlayer' },
	ELA: { name: 'Elastos', slug: 'elastos' },
	ENA: { name: 'Ethena', slug: 'ethena' },
	ENJ: { name: 'Enjin Coin', slug: 'enjin-coin' },
	ENS: { name: 'Ethereum Name Service', slug: 'ethereum-name-service' },
	EOS: { name: 'EOS', slug: 'eos' },
	ETC: { name: 'Ethereum Classic', slug: 'ethereum-classic' },
	ETH: { name: 'Ethereum', slug: 'ethereum' },
	ETHFI: { name: 'Ether.fi', slug: 'ether-fi' },
	EURR: { name: 'eToro Euro', slug: 'etoro-euro' },
	EWT: { name: 'Energy Web Token', slug: 'energy-web-token' },
	FARM: { name: 'Harvest Finance', slug: 'harvest-finance' },
	FET: { name: 'Fetch.ai', slug: 'fetch-ai' },
	FIDA: { name: 'Bonfida', slug: 'bonfida' },
	FIL: { name: 'Filecoin', slug: 'filecoin' },
	FIS: { name: 'Stafi', slug: 'stafi' },
	FLOKI: { name: 'FLOKI', slug: 'floki' },
	FLOW: { name: 'Flow', slug: 'flow' },
	FLR: { name: 'Flare', slug: 'flare' },
	FORT: { name: 'Forta', slug: 'forta' },
	FORTH: { name: 'Ampleforth Governance Token', slug: 'ampleforth-governance-token' },
	FOX: { name: 'ShapeShift FOX Token', slug: 'shapeshift-fox-token' },
	FWOG: { name: 'Froggies Token', slug: 'froggies-token' },
	G: { name: 'G', slug: 'g' },
	GFI: { name: 'Goldfinch', slug: 'goldfinch' },
	GIGA: { name: 'GIGA', slug: 'giga' },
	GLM: { name: 'Golem', slug: 'golem' },
	GLMR: { name: 'Moonbeam', slug: 'moonbeam' },
	GMT: { name: 'STEPN', slug: 'stepn' },
	GNO: { name: 'Gnosis', slug: 'gnosis' },
	GOAT: { name: 'GoatCoin', slug: 'goatcoin' },
	GODS: { name: 'Gods Unchained', slug: 'gods-unchained' },
	GRT: { name: 'The Graph', slug: 'the-graph' },
	GTC: { name: 'Gitcoin', slug: 'gitcoin' },
	HBAR: { name: 'Hedera', slug: 'hedera' },
	HFT: { name: 'Hashflow', slug: 'hashflow' },
	HIGH: { name: 'Highstreet', slug: 'highstreet' },
	HMSTR: { name: 'Hamster Kombat', slug: 'hamster-kombat' },
	HNT: { name: 'Helium', slug: 'helium' },
	HONEY: { name: 'Hivemapper', slug: 'hivemapper' },
	ICP: { name: 'Internet Computer', slug: 'internet-computer' },
	IDEX: { name: 'IDEX', slug: 'idex' },
	ILV: { name: 'Illuvium', slug: 'illuvium' },
	IMX: { name: 'Immutable X', slug: 'immutable-x' },
	INJ: { name: 'Injective', slug: 'injective' },
	IO: { name: 'IO.NET', slug: 'io-net' },
	IOTX: { name: 'IoTeX', slug: 'iotex' },
	JASMY: { name: 'JasmyCoin', slug: 'jasmycoin' },
	JTO: { name: 'Jito', slug: 'jito' },
	JUP: { name: 'Jupiter', slug: 'jupiter' },
	KARRAT: { name: 'Karrat', slug: 'karrat' },
	KAS: { name: 'Kaspa', slug: 'kaspa' },
	KNC: { name: 'Kyber Network', slug: 'kyber-network' },
	KSM: { name: 'Kusama', slug: 'kusama' },
	LCX: { name: 'LCX', slug: 'lcx' },
	LDO: { name: 'Lido DAO', slug: 'lido-dao' },
	LIFIII: { name: 'LifeLine', slug: 'lifeline' },
	LINK: { name: 'Chainlink', slug: 'chainlink' },
	LIT: { name: 'Litentry', slug: 'litentry' },
	LOKA: { name: 'League of Kingdoms', slug: 'league-of-kingdoms' },
	LPT: { name: 'Livepeer', slug: 'livepeer' },
	LQTY: { name: 'Liquity', slug: 'liquity' },
	LRC: { name: 'Loopring', slug: 'loopring' },
	LRDS: { name: 'Lords', slug: 'lords' },
	LTC: { name: 'Litecoin', slug: 'litecoin' },
	LUNA: { name: 'Terra', slug: 'terra' },
	MAGIC: { name: 'MAGIC', slug: 'magic' },
	MANA: { name: 'Decentraland', slug: 'decentraland' },
	MASK: { name: 'Mask Network', slug: 'mask-network' },
	MATH: { name: 'MATH', slug: 'math' },
	MATIC: { name: 'Polygon', slug: 'polygon' },
	MDT: { name: 'Measurable Data Token', slug: 'measurable-data-token' },
	ME: { name: 'ME', slug: 'me' },
	MEME: { name: 'Memecoin', slug: 'memecoin' },
	METIS: { name: 'Metis', slug: 'metis' },
	MKR: { name: 'Maker', slug: 'maker' },
	MNDE: { name: 'Marinade', slug: 'marinade' },
	MNT: { name: 'Mantle', slug: 'mantle' },
	MOG: { name: 'Mog Coin', slug: 'mog-coin' },
	MOODENG: { name: 'MoodEngine', slug: 'moodengine' },
	MOON: { name: 'MoonToken', slug: 'moontoken' },
	MORPHO: { name: 'Morpho', slug: 'morpho' },
	MXC: { name: 'MXC', slug: 'mxc' },
	NCT: { name: 'PolySwarm', slug: 'polyswarm' },
	NEAR: { name: 'NEAR Protocol', slug: 'near-protocol' },
	NEO: { name: 'Neo', slug: 'neo' },
	NEXO: { name: 'Nexo', slug: 'nexo' },
	NKN: { name: 'NKN', slug: 'nkn' },
	NMR: { name: 'Numeraire', slug: 'numeraire' },
	NODL: { name: 'Nodle', slug: 'nodle' },
	NOS: { name: 'Nosana', slug: 'nosana' },
	OCEAN: { name: 'Ocean Protocol', slug: 'ocean-protocol' },
	OGN: { name: 'Origin Protocol', slug: 'origin-protocol' },
	OMNI: { name: 'Omni Network', slug: 'omni-network' },
	ONDO: { name: 'Ondo Finance', slug: 'ondo-finance' },
	OP: { name: 'Optimism', slug: 'optimism' },
	ORCA: { name: 'Orca', slug: 'orca' },
	OSMO: { name: 'Osmosis', slug: 'osmosis' },
	OXT: { name: 'Orchid', slug: 'orchid' },
	PAXG: { name: 'PAX Gold', slug: 'pax-gold' },
	PENDLE: { name: 'Pendle', slug: 'pendle' },
	PEPE: { name: 'Pepe', slug: 'pepe' },
	PERP: { name: 'Perpetual Protocol', slug: 'perpetual-protocol' },
	PHA: { name: 'Phala Network', slug: 'phala-network' },
	PIRATE: { name: 'Pirate Chain', slug: 'pirate-chain' },
	PNG: { name: 'Pangolin', slug: 'pangolin' },
	PNUT: { name: 'Peanut', slug: 'peanut' },
	POL: { name: 'Proof Of Liquidity', slug: 'proof-of-liquidity' },
	POPCAT: { name: 'Popcat', slug: 'popcat' },
	POWR: { name: 'Power Ledger', slug: 'power-ledger' },
	PRCL: { name: 'Parcel', slug: 'parcel' },
	PRIME: { name: 'Prime', slug: 'prime' },
	PRO: { name: 'Propy', slug: 'propy' },
	PYR: { name: 'Vulcan Forged', slug: 'vulcan-forged' },
	PYTH: { name: 'Pyth Network', slug: 'pyth-network' },
	PYUSD: { name: 'PayPal USD', slug: 'paypal-usd' },
	QI: { name: 'QiDao', slug: 'qidao' },
	QNT: { name: 'Quant', slug: 'quant' },
	RARE: { name: 'SuperRare', slug: 'superrare' },
	RARI: { name: 'Rarible', slug: 'rarible' },
	REN: { name: 'Ren', slug: 'ren' },
	RENDER: { name: 'Render', slug: 'render' },
	REQ: { name: 'Request', slug: 'request' },
	REZ: { name: 'Renzo', slug: 'renzo' },
	RLUSD: { name: 'RLUSD', slug: 'rlusd' },
	RONIN: { name: 'Ronin', slug: 'ronin' },
	ROSE: { name: 'Oasis Network', slug: 'oasis-network' },
	RPL: { name: 'Rocket Pool', slug: 'rocket-pool' },
	RSR: { name: 'Reserve Rights', slug: 'reserve-rights' },
	SAFE: { name: 'Safe', slug: 'safe' },
	SAMO: { name: 'Samoyedcoin', slug: 'samoyedcoin' },
	SAND: { name: 'The Sandbox', slug: 'the-sandbox' },
	SBR: { name: 'Saber', slug: 'saber' },
	SCRT: { name: 'Secret', slug: 'secret' },
	SD: { name: 'Stader', slug: 'stader' },
	SEI: { name: 'Sei', slug: 'sei' },
	SGB: { name: 'Songbird', slug: 'songbird' },
	SHDW: { name: 'Shadow Token', slug: 'shadow-token' },
	SHIB: { name: 'Shiba Inu', slug: 'shiba-inu' },
	SHPING: { name: 'SHPING', slug: 'shping' },
	SKL: { name: 'SKALE', slug: 'skale' },
	SKY: { name: 'Skycoin', slug: 'skycoin' },
	SOL: { name: 'Solana', slug: 'solana' },
	SPA: { name: 'Sperax', slug: 'sperax' },
	SPELL: { name: 'Spell Token', slug: 'spell-token' },
	SPX: { name: 'SPX6900', slug: 'spx6900' },
	STRD: { name: 'Stride', slug: 'stride' },
	STX: { name: 'Stacks', slug: 'stacks' },
	SUI: { name: 'Sui', slug: 'sui' },
	SUKU: { name: 'SUKU', slug: 'suku' },
	SUPER: { name: 'SuperFarm', slug: 'superfarm' },
	SUSHI: { name: 'SushiSwap', slug: 'sushiswap' },
	SWELL: { name: 'Swell Network', slug: 'swell-network' },
	SWFTC: { name: 'SwftCoin', slug: 'swftcoin' },
	SYRUP: { name: 'Syrup Finance', slug: 'syrup-finance' },
	TAO: { name: 'Bittensor', slug: 'bittensor' },
	TIA: { name: 'Celestia', slug: 'celestia' },
	TOKE: { name: 'Tokemak', slug: 'tokemak' },
	TON: { name: 'Toncoin', slug: 'toncoin' },
	TRAC: { name: 'OriginTrail', slug: 'origintrail' },
	TRB: { name: 'Tellor', slug: 'tellor' },
	TRU: { name: 'TrueFi', slug: 'truefi' },
	TRUMP: { name: 'TrumpCoin', slug: 'trumpcoin' },
	TRX: { name: 'TRON', slug: 'tron' },
	TURBO: { name: 'Turbo', slug: 'turbo' },
	UMA: { name: 'UMA', slug: 'uma' },
	UNI: { name: 'Uniswap', slug: 'uniswap' },
	UOS: { name: 'Ultra', slug: 'ultra' },
	USDC: { name: 'USD Coin', slug: 'usd-coin' },
	USDG: { name: 'USDG', slug: 'usdg' },
	USDT: { name: 'Tether', slug: 'tether' },
	UST: { name: 'TerraUSD', slug: 'terrausd' },
	VELO: { name: 'Velo', slug: 'velo' },
	VET: { name: 'VeChain', slug: 'vechain' },
	VOXEL: { name: 'Voxies', slug: 'voxies' },
	VTHO: { name: 'VeThor Token', slug: 'vethor-token' },
	W: { name: 'W', slug: 'w' },
	WAXL: { name: 'Wrapped Axelar', slug: 'wrapped-axelar' },
	WBTC: { name: 'Wrapped Bitcoin', slug: 'wrapped-bitcoin' },
	WCFG: { name: 'Wrapped Centrifuge', slug: 'wrapped-centrifuge' },
	WELL: { name: 'Well', slug: 'well' },
	WIF: { name: 'dogwifhat', slug: 'dogwifhat' },
	XCN: { name: 'Chain', slug: 'chain' },
	XLM: { name: 'Stellar', slug: 'stellar' },
	XMR: { name: 'Monero', slug: 'monero' },
	XRD: { name: 'Radix', slug: 'radix' },
	XRP: { name: 'XRP', slug: 'xrp' },
	XTZ: { name: 'Tezos', slug: 'tezos' },
	XYO: { name: 'XYO', slug: 'xyo' },
	YFI: { name: 'yearn.finance', slug: 'yearn-finance' },
	ZEC: { name: 'Zcash', slug: 'zcash' },
	ZETA: { name: 'ZetaChain', slug: 'zetachain' },
	ZETACHAIN: { name: 'ZetaChain', slug: 'zetachain' },
	ZK: { name: 'ZKSync', slug: 'zksync' },
	ZRO: { name: 'LayerZero', slug: 'layerzero' },
	ZRX: { name: '0x', slug: '0x' }
}

module.exports = {
	symbolMappings
}
